FROM mysql:5.6
ENV MYSQL_ROOT_PASSWORD i3lworks
ENV MYSQL_DATABASE oic
ENV MYSQL_USER oic_user
ENV MYSQL_PASSWORD dbsecret
CMD ["mysqld", "--character-set-server=latin1", "--collation-server=latin1_swedish_ci"]